# =====================================
# 🔧 Modifiche apportate:
# - Aggiunto `depends_on` per garantire che resource_catalog e database_adaptor vengano avviati prima dei servizi che li usano.
# - Aggiunto `restart: always` per i container critici (utile su Raspberry Pi per auto-riavvio).
# - 
# =====================================


version: "3.9"

services:
  telegram_bot:
    build: ./telegram_bot
    volumes:
      - ./shared:/app/shared
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: unless-stopped
    depends_on:
      - resource_catalog
      - database_adaptor

  violation_detection:
    build:
      context: ./violation_detection
      dockerfile: Dockerfile
    volumes:
      - ./shared:/app/shared
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog
      - database_adaptor

  infraction_sensor:
    build:
      context: ./violation_detection
      dockerfile: Dockerfile.sensor
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  thingspeak_adaptor:
    build:
      context: ./Sensors
      dockerfile: Dockerfile.thingspeak
    volumes:
      - ./shared:/app/shared
    restart: always
    depends_on:
      - resource_catalog

  pir_sensor:
    build:
      context: ./Sensors
      dockerfile: Dockerfile.pir
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  dht22_sensor:
    build:
      context: ./Sensors
      dockerfile: Dockerfile.dht22
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  button_sensor:
    build:
      context: ./Sensors
      dockerfile: Dockerfile.button
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  resource_catalog:
    build: ./resource_catalog
    volumes:
      - ./shared:/app/shared
    restart: always

  led_lcd_1:
    build:
      context: ./Lights
      dockerfile: Dockerfile.ledlcd1
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  led_light_2:
    build:
      context: ./Lights
      dockerfile: Dockerfile.ledlight2
    privileged: true
    volumes:
      - ./shared:/app/shared
      - /dev:/dev
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  road_ice_predictor:
    build:
      context: ./Lights/services
      dockerfile: Dockerfile.roadice
    volumes:
      - ./shared:/app/shared
      - ./linear_model.pkl:/app/linear_model.pkl:ro
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  led_manager:
    build:
      context: ./LedManager
      dockerfile: Dockerfile.ledmanager
    volumes:
      - ./shared:/app/shared
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  database_adaptor:
    build:
      context: ./database
      dockerfile: Dockerfile.dbadaptor
    volumes:
      - ./database/infraction_database.db:/app/infraction_database.db
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: always
    depends_on:
      - resource_catalog

  emergency_simulator:
    build:
      context: ./LedManager
      dockerfile: Dockerfile.emergencysim
    volumes:
      - ./shared:/app/shared
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: unless-stopped
    depends_on:
      - resource_catalog

  ice_risk_simulator:
    build:
      context: ./Lights/services
      dockerfile: Dockerfile.icesim
    volumes:
      - ./shared:/app/shared
      - ./resource_catalog/resource_catalog_info.json:/app/resource_catalog_info.json:ro
    restart: unless-stopped
    depends_on:
      - resource_catalog
