FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y python3-smbus i2c-tools libgpiod2 && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "LED_LCD1.py"]
