FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y libgpiod2 && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "LED_light2.py"]
