FROM python:3.10-slim

WORKDIR /app

COPY ThingSpeak_Adaptor.py ThingSpeak_Adaptor_info.json MyMQTT.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "ThingSpeak_Adaptor.py"]
