FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . .

# Aggiungi build tools necessari per sysv_ipc e pacchetti GPIO
RUN apt-get update && \
    apt-get install -y libgpiod2 gcc build-essential libffi-dev && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "Button.py"]