FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y libgpiod2 gcc build-essential libffi-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get update && apt-get install -y lgpio

CMD ["python", "DHT22.py"]
